CREATE DATABASE IF NOT EXISTS jad_voyage CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE jad_voyage;

CREATE TABLE IF NOT EXISTS reservations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  destination VARCHAR(100) NOT NULL,
  date DATE NOT NULL
);
